---
title: "p8105_hw5_tw3108"
author: "Tao Wu"
date: "2025-11-14"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r,message=FALSE,warning=FALSE}
library(tidyverse)
set.seed(123)
birthdaycheck = function(n) {
  birthdays = sample(1:365, size = n, replace = TRUE)
  any(duplicated(birthdays))
}
sim_data = function(n, time = 10000) {
   result = logical(time)
  for (i in 1:time) {
    result[i] = birthdaycheck(n)
  }
  tibble(
    groupsize = n,
    prob = mean(result)
  )
}
final = tibble()
for (n in 2:50) {
  sim = sim_data(n)
  final = bind_rows(final, sim)
}
final
final %>% 
  ggplot(aes(x = groupsize, y = prob)) +geom_point() + geom_line() +
  labs(
    x = "Group size",
    y = "Probability of shared birthday",
  ) + theme_minimal()
```

Problem 1
I think the result and plot are very reasonable, as the number of people in a group increases, the probability of shared birthday rises. It reaches 0.5 at sample size 23, which is consist with the actual theory. 
